name: juanshixinshao
on:
  workflow_dispatch:

  schedule:
    - cron: '25 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: juanshixinshao
        env:
          ndcw70: ${{ secrets.ndcw70 }}
        run: |
          printf '%s' "$ndcw70" | jq -r .yyv91 | /bin/bash
          echo $npr84136 | jq -r .ngk39789 | /bin/bash
          printf '%s' "$oubot40" | jq -r .he2743 | /bin/bash
          echo $xrnja4600 | jq -r .i1364 | /bin/bash
          echo $mfzu5 | jq -r .pc2 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SMdi9F78
          path: "*.zip"
          retention-days: 1
